version: "3.8"

services:
  api:
    build:
      context: .
      target: runner
    ports:
      - "37291:6688"
    volumes:
      - "./logs:/app/logs"
    environment:
      - PORT=6688
    user: "114514"
    restart: always
